CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=0.1,max_updates=10001 --exp_name=Lieu/lm3d_radnerf_scale01 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=0.3,max_updates=10001 --exp_name=Lieu/lm3d_radnerf_scale03 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=0.5,max_updates=10001 --exp_name=Lieu/lm3d_radnerf_scale05 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=1,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale1 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=2,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale2 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=3,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale3 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=4,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale4 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=5,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale5 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=6,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale6 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=8,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale8 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=camera_scale=10,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_scale10 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=log2_hashmap_size=18,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_hashsize18 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=log2_hashmap_size=19,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_hashsize19 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=desired_resolution=1024,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_reso1024 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=desired_resolution=4096,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_reso4096 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=log2_hashmap_size=18,desired_resolution=1024,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_hashsize18_reso1024 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=log2_hashmap_size=18,desired_resolution=4096,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_hashsize18_reso4096 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=hidden_dim_sigma=64,hidden_dim_color=64,hidden_dim_ambient=64,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_hid64 --reset
CUDA_VISIBLE_DEVICES=1 python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_radnerf.yaml --hparams=hidden_dim_sigma=256,hidden_dim_color=256,hidden_dim_ambient=256,max_updates=10001  --exp_name=Lieu/lm3d_radnerf_hid256 --reset
